# Generated by Django 4.0.2 on 2022-02-26 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='url',
        ),
    ]
