# Generated by Django 4.0.2 on 2022-08-15 06:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_friendship_friendship_follow_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='followees',
            field=models.ManyToManyField(related_name='+', through='accounts.FriendShip', to=settings.AUTH_USER_MODEL, verbose_name='フォロー中のユーザー'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='followers',
            field=models.ManyToManyField(related_name='+', through='accounts.FriendShip', to=settings.AUTH_USER_MODEL, verbose_name='フォローされているユーザー'),
        ),
    ]
